#!/bin/bash

COMPONENT=Redis
source components/common.sh
INFO "install redis"
yum install epel-release yum-utils -y &>>$LOG_FILE

STAT $?

#yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y
#yum-config-manager --enable remi
#yum install redis -y