#!/bin/bash

COMPONENT=Redis
source components/common.sh
INFO "install redis"
yum install epel-release yum-utils -y &>>$LOG_FILE
STAT $? "installed repos"
yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y &>>$LOG_FILE
yum-config-manager --enable remi &>>$LOG_FILE
yum install redis -y &>>$LOG_FILE
STAT $? "installed repos"

INFO "update the redis ip configuration"
sed -i 's/127.0.0.1/0.0.0.0/' /etc/redis.conf
INFO "restart redis database service"
systemctl enable redis
systemctl start redis
STAT $? "start the redis service"
