#!/bin/bash
common:
	@sh components/common.sh

frontend: common
	@sh components/frontend.sh
mongo: common
	@sh components/mongo.sh
catalogue: common
	@sh components/Catalogue.sh
Redis: common
	@sh components/Redis
user: common
	@sh components/User.sh
cart: common
	@sh components/cart.sh
